version: "3" # Docker compose version I am using
services:
  ml_service:
    container_name: ml_service
    restart: always # Docker will restart container if it exits
    build: ./ml_service # Build from ui_service directory
    ports:
      - "8000:8000"
  ui_service:
    container_name: ui_service
    restart: always
    build: ./ui_service # Build from ui_service directory
    depends_on:
      - ml_service
    ports:
      - "8001:8001" # Specify the port forwarding
    # Connect to the ml_service by sending request to container name and the open port for that container
    command: http://ml_service:8000/predict 